### PR TITLE
feat: Allow multiple paths with --filter flag

### PR DESCRIPTION
**Pull request by rsinnet**
# Pull Request

## Related Github Issues

- _[none]_

## Description

Update the type of the --filter flag so multiple paths or glob expressions can be passed as a comma-separated list.

## Security Implications

- _[none]_

## System Availability

- _[none]_

### CODE REVIEW

**Comment by rsinnet** [comment]
Do I need to do anything to get this assigned?

**Comment by amontalban** [comment]
I really need this feature 🙏 

@dmattia what is needed to have this merged? Thank you!

**Comment by Almenon** [comment]
@amontalban I reviewed the code and it looks good. I still need to pass it by chatgpt. The code fails a few tests when I run it locally on Windows. It's been a long time since this PR was created, so the PR will need to be rebased on top of master and any test failures fixed. I would wait a bit* to see if @rsinnet will take this on, otherwise you can create your own PR.

image

\* wait time depending on how patient you are, I would suggest a day at least

**Comment by rsinnet** [comment]
> @amontalban I reviewed the code and it looks good. I still need to pass it by chatgpt. The code fails a few tests when I run it locally on Windows. It's been a long time since this PR was created, so the PR will need to be rebased on top of master and any test failures fixed. I would wait a bit* to see if @rsinnet will take this on, otherwise you can create your own PR.
> 
> image
> 
> * wait time depending on how patient you are, I would suggest a day at least

Sorry, guys. I left the organization and no longer have push access to the branch. Maybe @shaurya-pednekar or @imjaya can help out here?

**Comment by Almenon** [comment]
> The code fails a few tests when I run it locally on Windows

Ignore this part, my bad. This was because https://github.com/transcend-io/terragrunt-atlantis-config/pull/311 was not merged in yet. Once I merged it in all the tests passed with a copy-pasted set of your changes 🎉 . The PR will still need to be rebased or recreated to make sure the tests pass in CI.

**Comment by amontalban** [comment]
> > The code fails a few tests when I run it locally on Windows
> 
> Ignore this part, my bad. This was because #311 was not merged in yet. Once I merged it in all the tests passed with a copy-pasted set of your changes 🎉 . The PR will still need to be rebased or recreated to make sure the tests pass in CI.

@Almenon created https://github.com/transcend-io/terragrunt-atlantis-config/pull/328 with latest `master` code.

Thank you for checking this out!

**Comment by Almenon** [comment]
I just merged in the new PR, closing. Thanks for the contribution!

**Pull request closed without merging**
