### PR TITLE
Update Terragrunt Version & Bump Patch Version

### PR DESCRIPTION
**Pull request by angeloskaltsikis**
Updates Terragrunt Version in Go mod, in order to support `sops_decrypt_file`
to encrypt/decrypt sensitive data in your git repo.
This has been introduced to the
[v0.23.18](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.18)
but this PR updates Terragrunt to the latest current version (`v0.23.31`).

### CODE REVIEW

**Comment by angeloskaltsikis** [comment]
Hey mate @dmattia,
When you have some free time please take a look into this :-)

**Comment by dmattia** [comment]
Thanks for this!

**Comment by angeloskaltsikis** [comment]
@dmattia Thanks for the quick review. Can you also cut a new release/tag?

**Comment by dmattia** [comment]
Sure thing :) Just pushed up a new release: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.4.4

**Pull request merged**
