### PR TITLE
add dependency from terraform module source

### PR DESCRIPTION
**Pull request by dmattia**
Bringing https://github.com/transcend-io/terragrunt-atlantis-config/pull/156 back to life.

Unfortunately, I merged it after testing that ubuntu tests passed, but the windows tests failed.

On this PR, both platforms should run

Closes https://github.com/transcend-io/terragrunt-atlantis-config/issues/154

### CODE REVIEW

**Comment by dmattia** [comment]
@IndraGunawan are you able to fix the code to pass tests on Windows?

**Comment by IndraGunawan** [comment]
@dmattia problem fixed in this PR #163 
once #163 PR get merge then you can merge this PR

**Comment by mqmr** [comment]
@dmattia I think that changes from this PR do not work properly when `source` is an absolute path, e.g.
```
terraform {
  source = "${get_parent_terragrunt_dir()}/units//unitA"
}
```
generating fails on this call - https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/generate.go#L145 - because the joined path doesn't exist

**Comment by dmattia** [comment]
@mqmr Noted, thanks! Can you please open that up in a new Issue, and I will put some thoughts there?

**Comment by mqmr** [comment]
Sure thing, @dmattia. Should've done that straight away.

https://github.com/transcend-io/terragrunt-atlantis-config/issues/164

**Pull request merged**
