### PR TITLE
add depends_on; fix execution_order_group 0.

### PR DESCRIPTION
**Pull request by pseudomorph**
# Pull Request

## Related Github Issues

- #296 
- #319 

## Description

Adds functionality for `depends_on`
Fixes bug where the base execution_group (0) was not explicitly given.

## Security Implications

- _[none]_

## System Availability

- _[none]_

### CODE REVIEW

**Comment by pseudomorph** [comment]
Blocked by: #311

**Comment by Almenon** [comment]
I just merged in #311, can you rebase please? That might fix the failing windows test.

**Comment by Almenon** [comment]
I reviewed the code, it looks good but I'll hold off on approving it until the tests pass. Also if you could update the readme to add the new flag that would be great.

**Comment by pseudomorph** [comment]
@Almenon - Any idea why tests would be failing for Windows?

**Comment by Almenon** [comment]
Not sure. Based on the diff it looks like `DependsOn` should be a list with three elements, but for some reason it's missing one of the expected elements "depender_on_depender_nested". The test fails on my machine too, so it's not just a CI-specific error.

**Comment by Almenon** [comment]
It's also weird because in your code I don't see anything specific to windows / linux 🤔

**Comment by jon-walton** [comment]
Here's a patch to get you started.

```diff
diff --git a/cmd/generate.go b/cmd/generate.go
index f274f83..70b7532 100644
--- a/cmd/generate.go
+++ b/cmd/generate.go
@@ -828,7 +828,7 @@ func main(cmd *cobra.Command, args []string) error {
                                dependsOnList := []string{}
                                // choose order group based on dependencies
                                for _, dep := range project.Autoplan.WhenModified {
-                                       depPath := filepath.Dir(filepath.Join(project.Dir, dep))
+                                       depPath := filepath.ToSlash(filepath.Dir(filepath.Join(project.Dir, dep)))
                                        if depPath == project.Dir {
                                                // skip dependency on oneself
                                                continue
```

A project's `WhenModified` is forced with unix path separators via `relativeDependencies = append(relativeDependencies, filepath.ToSlash(relativePath))` yet, we're comparing it against `depPath` which was made with OS specific path separators, quite subtle

The tests `TestWithExecutionOrderGroupsAndDependsOn` and `TestWithDependsOn` now pass for me

**Comment by pseudomorph** [comment]
Thanks @jon-walton !

**Review by Almenon — APPROVED** [review]

**Comment by Almenon** [comment]
Approved, but the release CI process for releasing a new build with this change is broken. Can you review https://github.com/transcend-io/terragrunt-atlantis-config/pull/332 please? Hopefully that will fix it.

**Comment by Almenon** [comment]
v1.18.0 is out with this change now :)

**Pull request merged**
